### ISSUE TITLE
Enable docs build on push to development

### ISSUE THREAD

**Issue by tiagoafpereira** [inductiva/inductiva#1281]
`gh-pages/en/development` is only updated (via GitHub Action) when pushing to `main` branch:

```yaml
name: GH Pages Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
```

We should have it updated when pushing to `development` as well:

```yaml
name: GH Pages Deploy

on:
  push:
    branches: [main, development]
    paths-ignore:
      - README.md

```
